### array creation

from list

In [132]:
import numpy as np

my_list = [1,2,3,4,5]
print(np.array(my_list))

[1 2 3 4 5]


with 'arange' function

In [133]:
# np.arrange(st, en, step)
print(np.arange(0, 10, 2))
print(np.arange(0, 10, 1))

[0 2 4 6 8]
[0 1 2 3 4 5 6 7 8 9]


array of zeroes (ones)

In [134]:
# one dim array
np.zeros(10)
# multi-dim array row - first columns - second
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

float range array creation

In [135]:
# args: start point, end point, total count of points
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

create identity matrix

In [136]:
# args: matrix size
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

random arrays

In [137]:
# one dim list; args: count of random numbers from uniform distribution [0, 1)
np.random.rand(5)
# several dim list; args: sequence represents dimensions (general case)
np.random.rand(5,5)

array([[0.90777287, 0.37294241, 0.85888946, 0.81419445, 0.37943415],
       [0.97456516, 0.99771109, 0.61492305, 0.33870858, 0.37554303],
       [0.97890889, 0.50862656, 0.36508883, 0.8516201 , 0.7406956 ],
       [0.28218708, 0.88789139, 0.2041102 , 0.77621935, 0.0191785 ],
       [0.5685741 , 0.93237566, 0.27648048, 0.60544218, 0.39978087]])

In [138]:
# using random numbers from standard normal distribution
np.random.randn(5)  # one dim case
np.random.randn(3,3,3)  # several dim case

# array of random integers
# randint(low (inclusive), high(exclusive), size) returns integers from discrete uniform distribution
np.random.randint(-10, 10, 100)
np.random.randint(10)   # one random random number from 0 to low-1

6

reshape method

In [144]:
arr = np.arange(1,11)
arr.reshape((2,5))      # remember about reshape error!
arr.reshape((5,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

min(), max(), argmax(), argmin(), methods

In [147]:
arr = np.array([1,2,3,4])
arr.min()   # 1
arr.max()   # 4
arr.argmin()    # min position
arr.argmax()    # max position

0

getting array shape

In [151]:
arr = np.arange(1,16)
arr = arr.reshape(5,3)
arr.shape       # (5,3)

(5, 3)

getting array data type

In [153]:
arr = np.arange(1, 10, 0.5)
arr.dtype   # float64

dtype('float64')