In [2]:
from TPNN.tools.CNNarchitecture import *
from TPNN.tools.optimizers import Adam
import numpy as np

## Test net creation

In [2]:
# create net:
cnnLayer = CNNlayer((1, 10, 10), sigmoid, 2, (3,3), 1)
poolingLayer = MaxPoolingLayer((2,2), cnnLayer.output_shape)
reformatLayer = ReformatLayer(poolingLayer.output_shape)
denseLayer = DenseLayer(sigmoid, 10, reformatLayer.output_shape[0])
softmaxLayer = SoftmaxLayer(10)

net = Net()
net.add_layer(cnnLayer)
net.add_layer(poolingLayer)
net.add_layer(reformatLayer)
net.add_layer(denseLayer)
net.add_layer(softmaxLayer)
net.print_config()

Layers count: 5
layers configuration: 

CNN layer
 input shape - (1, 10, 10); output shape - (2, 8, 8)
 cores: 
[0]:
     0.7070407743116518 -0.0997372196300661 0.6922620576463498 
     0.024788605506006478 -0.5869277953944796 -0.6130906721311149 
     0.03617945689252222 -0.8413844919144033 -0.7242966865532816 
[1]:
     0.8613372814220874 0.32655416241858126 -0.31692686890454946 
     0.33706205399243516 0.8689084304230359 -0.6709516557725015 
     0.18495214839070373 0.11791648192236504 0.2085855085178805 
 biases: 
     -0.5727297431328475 0.3982584410567205 

MaxPooling layer
 input shape - (2, 8, 8); output shape - (2, 4, 4)
 core shape: (2, 2)
 maximums positions:
[[[[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.

In [3]:
input_data = np.random.rand(1, 10, 10)

print("input:")
print(input_data)

input:
[[[0.54664461 0.49488608 0.95401174 0.19279533 0.10489976 0.59196797
   0.49046557 0.90683631 0.10140715 0.97010112]
  [0.70843652 0.096177   0.95622743 0.67801812 0.44193228 0.4515971
   0.57464976 0.41650927 0.90973637 0.60015517]
  [0.31105869 0.98972876 0.14653339 0.606798   0.5102243  0.02221437
   0.26952732 0.67044132 0.98605945 0.54829919]
  [0.20008519 0.96763605 0.66848164 0.83062202 0.17997199 0.87465754
   0.26994607 0.58203362 0.81408389 0.69738703]
  [0.68851994 0.94770846 0.83487305 0.33497106 0.78167657 0.42726741
   0.09180004 0.47719111 0.08699672 0.4811421 ]
  [0.4673319  0.24829895 0.70106331 0.27239271 0.15703104 0.25653733
   0.96040735 0.5355516  0.27479525 0.64728506]
  [0.63638602 0.34284641 0.72745579 0.16515132 0.31020975 0.55002303
   0.17733864 0.31809568 0.10974023 0.79932567]
  [0.06096947 0.48817163 0.05713495 0.748674   0.78935411 0.550996
   0.65306401 0.07357814 0.39396841 0.14629229]
  [0.78173637 0.92586507 0.02147337 0.30373761 0.44632917 0.

In [4]:
print(net.get_output(input_data))

result shape: (32,)
[0.09288644 0.09570438 0.05869583 0.11845946 0.06566501 0.10053165
 0.10393501 0.12508784 0.09901072 0.14002366]


## Test CNN layer output

In [5]:
def print_info(input, net):
    print("input:")
    print(input)
    print("net config")
    net.print_config()

cnnLayer = CNNlayer((2,4,4), ident, 2, (2,2), 2)
cores = np.array([np.eye(2), np.eye(2)])
cnnLayer.set_cores(cores)
cnnLayer.set_biases(np.array([1, 1]))

net = Net()
net.add_layer(cnnLayer)

input = np.array([np.eye(4),np.eye(4)])

print_info(input, net)

input:
[[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]]
net config
Layers count: 1
layers configuration: 

CNN layer
 input shape - (2, 4, 4); output shape - (2, 2, 2)
 cores: 
[0]:
     1.0 0.0 
     0.0 1.0 
[1]:
     1.0 0.0 
     0.0 1.0 
 biases: 
     1 1 



In [6]:
print(net.get_output(input))

[[[5. 1.]
  [1. 5.]]

 [[5. 1.]
  [1. 5.]]]


## Test pooling layer

In [7]:
net = Net()
poolingLayer = MaxPoolingLayer((2,2), (2,4,4))
net.add_layer(poolingLayer)

input = np.array([[[1,2,1,2], [1,2,1,2], [1,2,1,2], [1,2,1,2]], [[1,2,1,2], [1,2,1,2], [1,2,1,2], [1,2,1,2]]])

print_info(input, net)

input:
[[[1 2 1 2]
  [1 2 1 2]
  [1 2 1 2]
  [1 2 1 2]]

 [[1 2 1 2]
  [1 2 1 2]
  [1 2 1 2]
  [1 2 1 2]]]
net config
Layers count: 1
layers configuration: 

MaxPooling layer
 input shape - (2, 4, 4); output shape - (2, 2, 2)
 core shape: (2, 2)
 maximums positions:
[[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]]



In [8]:
print(net.get_output(input))

[[[2. 2.]
  [2. 2.]]

 [[2. 2.]
  [2. 2.]]]


## Test dense layer

In [9]:
denseLayer = DenseLayer(ident, 10, 10)
denseLayer.set_weighs(np.eye(10))
denseLayer.set_biases(np.zeros((10, 1)))

net = Net()
net.add_layer(denseLayer)

input = np.arange(0,10)

print_info(input, net)

input:
[0 1 2 3 4 5 6 7 8 9]
net config
Layers count: 1
layers configuration: 

Dense layer
 neuron count: 10
 input shape - (10,); output shape - (10,)
 weight matrix:
     1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 
     0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 
     0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 
     0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 
     0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 
     0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 
     0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 
     0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 
     0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 
     0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 
 biases vector: 
     0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 



In [10]:
net.get_output(input)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## Test reformat layer

In [11]:
net = Net()
reformatLayer = ReformatLayer((2, 4, 4))
net.add_layer(reformatLayer)

input = np.ones((2,4,4))

print_info(input, net)

input:
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
net config
Layers count: 1
layers configuration: 

Reformat layer
 input shape - (2, 4, 4); output shape - (32,)



In [12]:
net.get_output(input)

result shape: (32,)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Test softmax layer

In [13]:
net = Net()
softmaxLayer = SoftmaxLayer(10)
net.add_layer(softmaxLayer)

input = np.arange(1, 11)
print_info(input, net)

input:
[ 1  2  3  4  5  6  7  8  9 10]
net config
Layers count: 1
layers configuration: 

Softmax layer
 input shape - (10,); output shape - (10,)



In [14]:
output = net.get_output(input)
print(output)
print(np.sum(output))

[7.80134161e-05 2.12062451e-04 5.76445508e-04 1.56694135e-03
 4.25938820e-03 1.15782175e-02 3.14728583e-02 8.55520989e-02
 2.32554716e-01 6.32149258e-01]
1.0


In [15]:
import numpy as np
from TPNN.tools.functions import print_arrays
arr = np.zeros((3,3,3,3,3))
print_arrays(arr, " ")

 [0]:
    [0]:
          [0]:
                   0.0 0.0 0.0 
                   0.0 0.0 0.0 
                   0.0 0.0 0.0 

          [1]:
                   0.0 0.0 0.0 
                   0.0 0.0 0.0 
                   0.0 0.0 0.0 

          [2]:
                   0.0 0.0 0.0 
                   0.0 0.0 0.0 
                   0.0 0.0 0.0 

    [1]:
          [0]:
                   0.0 0.0 0.0 
                   0.0 0.0 0.0 
                   0.0 0.0 0.0 

          [1]:
                   0.0 0.0 0.0 
                   0.0 0.0 0.0 
                   0.0 0.0 0.0 

          [2]:
                   0.0 0.0 0.0 
                   0.0 0.0 0.0 
                   0.0 0.0 0.0 

    [2]:
          [0]:
                   0.0 0.0 0.0 
                   0.0 0.0 0.0 
                   0.0 0.0 0.0 

          [1]:
                   0.0 0.0 0.0 
                   0.0 0.0 0.0 
                   0.0 0.0 0.0 

          [2]:
                   0.0 0.0 0.0 
                   0.0 0

In [3]:
cnnLayer = CNNlayer((2, 10, 10), sigmoid, 2, (3,3), 1)
poolingLayer = MaxPoolingLayer((2,2), cnnLayer.output_shape)
reformatLayer = ReformatLayer(poolingLayer.output_shape)
denseLayer = DenseLayer(sigmoid, 10, reformatLayer.output_shape[0])
softmaxLayer = SoftmaxLayer(10)

net = Net()
net.add_layer(cnnLayer)
net.add_layer(poolingLayer)
net.add_layer(reformatLayer)
net.add_layer(denseLayer)
net.add_layer(softmaxLayer)
net.print_config()
net.need_debug = True
net.set_optimizer(Adam())

Layers count: 5
layers configuration: 

CNN layer
 input shape - (2, 10, 10); output shape - (2, 8, 8)
 cores: 
[0]:
     -0.7907793943410741 0.3246140217169706 -0.48421392757126336 
     0.09200887909501132 0.41592903011032956 -0.4384271079066655 
     0.9063566463635373 0.5482427673853383 0.09246946684982182 
[1]:
     0.33128836782290016 -0.7842896268029247 -0.20804913633466238 
     -0.8564059728646036 -0.7247790285363589 0.411954763158636 
     -0.18683967116331823 -0.47573456839754424 0.006187297568420513 
 biases: 
     0.5401230585655652 0.5165421850741263 

MaxPooling layer
 input shape - (2, 8, 8); output shape - (2, 4, 4)
 core shape: (2, 2)
 maximums positions:
[[[[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 

In [5]:
train_input = np.random.rand(2, 10, 10) * 2 - 1

expected_output = np.zeros((10,))
expected_output[1] = 1

train_input = train_input.reshape(1,2,10,10)
expected_output = expected_output.reshape(1,10)
net.train(Data(train_input, expected_output))

actual vector:(10,)
output vector:(10,)
CNN layer
  derivatives values:
    input derivatives:
      [0]:
         0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 
         0.0 0.0 0.0 -0.016584567669119643 0.009426447754728073 0.0 0.00744683710738192 -0.004676874620991329 0.0004682182452679267 0.0 
         0.0 -0.002513190136835662 0.01148675300444877 -0.021488226094991042 0.005488381243905797 -0.0056360166633063835 0.010265789272716114 -0.00631775112617609 -9.875277036588105e-05 0.0 
         0.0 0.0307665772978767 -0.005800591806764345 -0.014928801834552396 0.018697553519037177 -0.02584619394215027 0.030049746882626363 0.004978455953979886 0.0053723528356524365 0.0 
         0.0 0.02217005012257766 3.464207962267882e-05 -0.013846580964974379 -0.0007534584694559568 -0.02809273837819961 -0.003379100091385784 -0.0077657166525473866 -0.0036077570023116596 0.0 
         0.0 -0.009066296666389646 0.008810512742171797 0.027486718541165335 -0.018869410826248163 -0.037214656682625136 0.029684649641