In [1]:
from TPNN.tools.perceptron import*
import numpy as np

In [2]:
net = Net()
net.insert_layer(0, 1, ident)
net.insert_layer(1, 5, sigmoid)
net.insert_layer(2, 1, ident)
print(net.layers_count)
net.init_weights(1, np.array([[1,1,1,1,1]]))
net.init_weights(2, np.array([[1,1,1,1,1]]).transpose())
net.init_biases(1, np.array([1,1,1,1,1]))

net.print_net_config()

3
layers=3
[0]
 size=1
 act_function=<function ident at 0x062316A0>
 activations=[[0.]]
 weights:
     empty
--------------------------
[1]
 size=5
 act_function=<function sigmoid at 0x0A5DE778>
 activations=[[0. 0. 0. 0. 0.]]
 weights:
     |1 1 1 1 1 |

--------------------------
[2]
 size=1
 act_function=<function ident at 0x062316A0>
 activations=[[0.]]
 weights:
     |1 |
     |1 |
     |1 |
     |1 |
     |1 |

--------------------------


In [3]:
net.calc_output(np.array([1]))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[3.65529289 3.65529289 3.65529289 3.65529289 3.65529289]]



array([[3.65529289, 3.65529289, 3.65529289, 3.65529289, 3.65529289]])