In [1]:
from TPNN_2023.lab2.Perceptron import ConfigLevel
from TPNN_2023.lab2.metrics import mse
from TPNN_2023.lab2.tools import Adam
from TPNN_2023.lab3.rnn import RNNnet, RNNlayer, LOSS_TYPE
from TPNN_2023.lab2.activation_functions import *
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.figure_factory as ff
import plotly.graph_objects as go

In [2]:
data = np.random.normal(size=(1000, 4))
data

array([[ 0.92372907, -1.13747172, -0.90463108, -0.87955988],
       [-0.27387693, -0.31665286, -0.72746014, -0.69984871],
       [-0.73806779, -0.54786951,  0.4836572 , -0.95843509],
       ...,
       [-0.57116338, -0.46713493, -1.75632737,  1.03475068],
       [ 1.183086  ,  1.5540384 , -1.41156143,  1.93369647],
       [ 0.02711717, -1.44252073,  0.69719842,  0.98065411]])

In [3]:
df = pd.DataFrame(data=data, columns=['a', 'b', 'c', 'd'])
df

a         b         c         d
0    0.923729 -1.137472 -0.904631 -0.879560
1   -0.273877 -0.316653 -0.727460 -0.699849
2   -0.738068 -0.547870  0.483657 -0.958435
3    1.417889 -0.022848 -1.205443  0.517716
4   -0.071850  0.261442  0.828117  0.098154
..        ...       ...       ...       ...
995 -0.478805  1.034382 -0.018430 -2.564433
996 -0.593495  0.039279  1.886069  0.709159
997 -0.571163 -0.467135 -1.756327  1.034751
998  1.183086  1.554038 -1.411561  1.933696
999  0.027117 -1.442521  0.697198  0.980654

[1000 rows x 4 columns]

In [4]:
input_train_data = df[['a', 'b', 'c']].to_numpy()
output_train_data = df[['d']].to_numpy()

timestamps = 20
batch_count = data.shape[0] // timestamps

input_train_data = input_train_data.reshape((batch_count, timestamps, 3, 1))
output_train_data = output_train_data.reshape(batch_count, timestamps, 1, 1)
input_train_data

array([[[[ 0.92372907],
         [-1.13747172],
         [-0.90463108]],

        [[-0.27387693],
         [-0.31665286],
         [-0.72746014]],

        [[-0.73806779],
         [-0.54786951],
         [ 0.4836572 ]],

        ...,

        [[-1.33984561],
         [-1.73964226],
         [ 0.63736766]],

        [[-1.71286807],
         [-1.11836061],
         [ 1.2701125 ]],

        [[-0.03679841],
         [ 1.27998431],
         [ 1.23465787]]],


       [[[ 0.87286722],
         [ 0.50151968],
         [ 0.58454743]],

        [[-0.03278079],
         [ 0.99748053],
         [ 1.66026892]],

        [[-0.44121733],
         [ 1.47057613],
         [-0.88310965]],

        ...,

        [[-0.10676821],
         [ 0.11572403],
         [-0.24887304]],

        [[ 1.72728829],
         [ 1.42684666],
         [-0.66657717]],

        [[-0.34065969],
         [ 0.33386574],
         [ 0.04656613]]],


       [[[ 0.71724271],
         [-2.69933249],
         [ 2.22144696]],

      

In [5]:
rnn_net = RNNnet()
rnn_net.add_layer(RNNlayer(timestamps=timestamps, neuron_count=15, output_vector_shape=(1, 1), activation=th, input_vector_shape=(3, 1)))

In [6]:
rnn_net.calc_output(input_train_data[0])

array([[[-0.22284677]],

       [[ 0.11204928]],

       [[ 0.54260921]],

       [[-0.23872039]],

       [[ 0.52830345]],

       [[-0.0539086 ]],

       [[ 0.68037441]],

       [[ 0.03834378]],

       [[ 0.83096275]],

       [[ 0.16259712]],

       [[ 0.25286779]],

       [[ 0.43100286]],

       [[ 0.2633034 ]],

       [[ 0.22227072]],

       [[ 0.65493461]],

       [[ 0.37850868]],

       [[-0.26719791]],

       [[ 0.76840002]],

       [[ 0.89893439]],

       [[ 0.72390337]]])

In [7]:
rnn_net.set_loss(LOSS_TYPE.MAE)
rnn_net.train(input_train_data=input_train_data, target_train_data=output_train_data, optimizer=Adam(), epoch_count=100, lr=0.00000001)

loss=0.8523458640651934
loss=0.852299868933917
loss=0.8522213669122324
loss=0.8521138325852925
loss=0.8519769966200462
loss=0.8518101146195549
loss=0.851612363375106
loss=0.8513847806647018
loss=0.8511274782157398
loss=0.8508378213578502
loss=0.8505195848846029
loss=0.8501723254475894
loss=0.8497911131309802
loss=0.8493804776014616
loss=0.8489386516715833
loss=0.8484622253270375
loss=0.8479564050492217
loss=0.8474150344671532
loss=0.846837267088454
loss=0.8462346398957186
loss=0.845597782269092
loss=0.8449254622627765
loss=0.8442247656057386
loss=0.8434865747972486
loss=0.8427243425222118
loss=0.8419229835417442
loss=0.8410876877915621
loss=0.8402235162679367
loss=0.8393269093616169
loss=0.8384001137611343
loss=0.837441010718019
loss=0.8364478613265932
loss=0.8354270567210045
loss=0.8344057382884145
loss=0.8333651722649539
loss=0.8322786024375288
loss=0.8311441352987576
loss=0.8299709843991449
loss=0.8287732730754483
loss=0.8276324243003715
loss=0.8265265814955864
loss=0.82542027216084

In [8]:
predictions = rnn_net.predict(input_train_data)
predictions.shape

(50, 20, 1, 1)

In [9]:
predictions = predictions.reshape((batch_count, timestamps, 1))
predictions = predictions.flatten()
predictions

array([-2.83843188e-02,  2.80854551e-02,  9.01835479e-02,  1.41429735e-01,
       -9.40211484e-02, -2.61817207e-02,  1.39503492e-02, -8.45065291e-02,
        4.21318893e-01,  3.45513967e-02, -1.68558818e-01,  1.18933237e-01,
        7.59857923e-02, -2.09900010e-01,  1.35675197e-01,  3.45954367e-01,
       -2.06580144e-01,  1.51969438e-01,  5.29712314e-01,  3.20395348e-01,
       -8.71933089e-03,  1.10106665e-02,  8.18089875e-02,  1.86900232e-01,
        8.70160684e-02,  1.65223113e-01, -1.06132625e-01, -2.06986156e-01,
       -2.06797528e-01,  1.74312582e-01,  4.04973152e-01,  3.65306428e-01,
        1.90024970e-01,  3.40387859e-02, -1.78313673e-01,  2.07084585e-01,
        2.88416572e-01,  4.91835780e-01,  1.63838827e-02, -1.06984050e-01,
        4.13868918e-01,  1.71982093e-01, -5.92724317e-02,  2.27462728e-01,
        3.13633134e-01, -8.00879845e-02,  3.07188756e-01,  5.94129748e-02,
       -1.65500171e-01,  1.06196759e-01,  1.25508827e-02,  2.66695333e-01,
       -3.43322841e-02,  

In [10]:
def plot_approximation(predicted_data, dst_data, attribute_name, mode: str):
    assert predicted_data.shape == dst_data.shape

    comparison_graphic = go.Figure()

    x = np.arange(1, predicted_data.shape[0] + 1)
    y_actual = dst_data
    y_predicted = predicted_data

    comparison_graphic.add_trace(go.Scatter(x=x, y=y_actual, mode=mode, name=attribute_name + ' actual graphic'))
    comparison_graphic.add_trace(go.Scatter(x=x, y=y_predicted, mode=mode, name=attribute_name + ' predicted'))

    comparison_graphic.update_layout(
    height= 1000,
    width = 4000,
    title_text=attribute_name
    )
    return comparison_graphic

In [11]:
base_dir = '../plots/lab3/'
comparison_graphic = plot_approximation(predictions, output_train_data.flatten(), 'd','markers')
comparison_graphic.write_image(base_dir + "rnn_test.pdf")

In [12]:
predictions[0]

-0.028384318813511514

In [13]:
predictions[1]

0.028085455064343706

In [14]:
predictions[20]

-0.008719330885138054

In [15]:
predictions[21]

0.011010666459742031

In [16]:
input_train_data

array([[[[ 0.92372907],
         [-1.13747172],
         [-0.90463108]],

        [[-0.27387693],
         [-0.31665286],
         [-0.72746014]],

        [[-0.73806779],
         [-0.54786951],
         [ 0.4836572 ]],

        ...,

        [[-1.33984561],
         [-1.73964226],
         [ 0.63736766]],

        [[-1.71286807],
         [-1.11836061],
         [ 1.2701125 ]],

        [[-0.03679841],
         [ 1.27998431],
         [ 1.23465787]]],


       [[[ 0.87286722],
         [ 0.50151968],
         [ 0.58454743]],

        [[-0.03278079],
         [ 0.99748053],
         [ 1.66026892]],

        [[-0.44121733],
         [ 1.47057613],
         [-0.88310965]],

        ...,

        [[-0.10676821],
         [ 0.11572403],
         [-0.24887304]],

        [[ 1.72728829],
         [ 1.42684666],
         [-0.66657717]],

        [[-0.34065969],
         [ 0.33386574],
         [ 0.04656613]]],


       [[[ 0.71724271],
         [-2.69933249],
         [ 2.22144696]],

      

In [17]:
batch1 = input_train_data[0]
batch1

array([[[ 0.92372907],
        [-1.13747172],
        [-0.90463108]],

       [[-0.27387693],
        [-0.31665286],
        [-0.72746014]],

       [[-0.73806779],
        [-0.54786951],
        [ 0.4836572 ]],

       [[ 1.41788925],
        [-0.02284799],
        [-1.20544314]],

       [[-0.07184993],
        [ 0.26144249],
        [ 0.82811743]],

       [[ 0.98159252],
        [ 0.64023739],
        [ 0.03897403]],

       [[-0.84651034],
        [ 2.27629457],
        [ 1.25638064]],

       [[ 0.48775488],
        [ 0.34133853],
        [-0.37123545]],

       [[ 0.02557915],
        [-0.64372122],
        [ 0.75442549]],

       [[ 0.9097987 ],
        [ 1.93436584],
        [ 0.75242647]],

       [[ 1.31620561],
        [ 0.47762858],
        [-0.54077623]],

       [[ 0.50756881],
        [ 0.28225424],
        [ 0.02713459]],

       [[ 2.04028758],
        [ 0.4745437 ],
        [ 0.3647475 ]],

       [[-0.37169323],
        [ 0.01434111],
        [ 0.27868738]],

      

In [18]:
batch2 = input_train_data[1]
batch2

array([[[ 0.87286722],
        [ 0.50151968],
        [ 0.58454743]],

       [[-0.03278079],
        [ 0.99748053],
        [ 1.66026892]],

       [[-0.44121733],
        [ 1.47057613],
        [-0.88310965]],

       [[ 0.61318417],
        [-0.86187891],
        [-1.20165702]],

       [[-1.49442408],
        [ 0.18794759],
        [-0.00930218]],

       [[ 0.2656131 ],
        [ 0.69397945],
        [ 1.96695221]],

       [[ 1.94513478],
        [ 1.03989616],
        [-1.9972397 ]],

       [[ 0.3077015 ],
        [ 1.87066926],
        [-1.177588  ]],

       [[ 1.44811539],
        [ 1.87538763],
        [-0.02173624]],

       [[-1.93019243],
        [ 0.53840209],
        [ 1.37372174]],

       [[-0.40193205],
        [ 1.35100634],
        [ 0.12232104]],

       [[-0.82581552],
        [-0.52674919],
        [ 0.22531951]],

       [[-1.23818148],
        [-0.31680109],
        [-2.49797065]],

       [[-0.0230106 ],
        [ 1.2201597 ],
        [-0.18336307]],

      

In [19]:
output1 = rnn_net.calc_output(batch1)
output1

array([[[-0.02838432]],

       [[ 0.02808546]],

       [[ 0.09018355]],

       [[ 0.14142973]],

       [[-0.09402115]],

       [[-0.02618172]],

       [[ 0.01395035]],

       [[-0.08450653]],

       [[ 0.42131889]],

       [[ 0.0345514 ]],

       [[-0.16855882]],

       [[ 0.11893324]],

       [[ 0.07598579]],

       [[-0.20990001]],

       [[ 0.1356752 ]],

       [[ 0.34595437]],

       [[-0.20658014]],

       [[ 0.15196944]],

       [[ 0.52971231]],

       [[ 0.32039535]]])

In [20]:
output2 = rnn_net.calc_output(batch2)
output2

array([[[-0.00871933]],

       [[ 0.01101067]],

       [[ 0.08180899]],

       [[ 0.18690023]],

       [[ 0.08701607]],

       [[ 0.16522311]],

       [[-0.10613263]],

       [[-0.20698616]],

       [[-0.20679753]],

       [[ 0.17431258]],

       [[ 0.40497315]],

       [[ 0.36530643]],

       [[ 0.19002497]],

       [[ 0.03403879]],

       [[-0.17831367]],

       [[ 0.20708459]],

       [[ 0.28841657]],

       [[ 0.49183578]],

       [[ 0.01638388]],

       [[-0.10698405]]])

In [21]:
pred = rnn_net.predict(input_train_data)
pred[0]

array([[[-0.02838432]],

       [[ 0.02808546]],

       [[ 0.09018355]],

       [[ 0.14142973]],

       [[-0.09402115]],

       [[-0.02618172]],

       [[ 0.01395035]],

       [[-0.08450653]],

       [[ 0.42131889]],

       [[ 0.0345514 ]],

       [[-0.16855882]],

       [[ 0.11893324]],

       [[ 0.07598579]],

       [[-0.20990001]],

       [[ 0.1356752 ]],

       [[ 0.34595437]],

       [[-0.20658014]],

       [[ 0.15196944]],

       [[ 0.52971231]],

       [[ 0.32039535]]])

In [22]:
pred[1]

array([[[-0.00871933]],

       [[ 0.01101067]],

       [[ 0.08180899]],

       [[ 0.18690023]],

       [[ 0.08701607]],

       [[ 0.16522311]],

       [[-0.10613263]],

       [[-0.20698616]],

       [[-0.20679753]],

       [[ 0.17431258]],

       [[ 0.40497315]],

       [[ 0.36530643]],

       [[ 0.19002497]],

       [[ 0.03403879]],

       [[-0.17831367]],

       [[ 0.20708459]],

       [[ 0.28841657]],

       [[ 0.49183578]],

       [[ 0.01638388]],

       [[-0.10698405]]])

In [23]:
input_train_data

array([[[[ 0.92372907],
         [-1.13747172],
         [-0.90463108]],

        [[-0.27387693],
         [-0.31665286],
         [-0.72746014]],

        [[-0.73806779],
         [-0.54786951],
         [ 0.4836572 ]],

        ...,

        [[-1.33984561],
         [-1.73964226],
         [ 0.63736766]],

        [[-1.71286807],
         [-1.11836061],
         [ 1.2701125 ]],

        [[-0.03679841],
         [ 1.27998431],
         [ 1.23465787]]],


       [[[ 0.87286722],
         [ 0.50151968],
         [ 0.58454743]],

        [[-0.03278079],
         [ 0.99748053],
         [ 1.66026892]],

        [[-0.44121733],
         [ 1.47057613],
         [-0.88310965]],

        ...,

        [[-0.10676821],
         [ 0.11572403],
         [-0.24887304]],

        [[ 1.72728829],
         [ 1.42684666],
         [-0.66657717]],

        [[-0.34065969],
         [ 0.33386574],
         [ 0.04656613]]],


       [[[ 0.71724271],
         [-2.69933249],
         [ 2.22144696]],

      